name: THgame
main: himamajin.niconico.thgame.Main
version: 1.0
commands:
   toso:
      description: dm [0~]
      usage: /dm [0~100]
      permission: dm.set
      permission-message: You don't have permission.
      default: op